### ISSUE TITLE
add room guid support

### ISSUE THREAD

**Issue by saerdnaer** [Kunsi/scheduled-plugin-pretalx-broadcast-tools#4]
IST:  Wird im Quellsystem Raum umbenannt muss aktuell in der Info-Beamer der Raumname von Hand nachgezogen werden
SOLL: Der Auswahl/Mapping eines PIs auf einen Raum soll nicht nur per Raumname sondern auch per Raum GUID statt finden. Wird ein Raum umbenannt schlägt sich der neue Name automatisch in Infobeamer Config durch und überschreibt den alten Namen

<img width="781" alt="image" src="https://github.com/Kunsi/scheduled-plugin-pretalx-broadcast-tools/assets/40266/ef8f873c-0d44-4ee4-b04a-a904897508ba">

**Comment by Kunsi** [comment]
Gute Idee. Braucht vermutlich zuerst die Anpassung in pretalx-broadcast-tools, oder ein pretalx-release mit den schema-konformen JSON-outputs.

**Comment by Kunsi** [comment]
Weils grade in einem Raum kaputtgeht: Wir müssen dann wohl ein Feature einbauen, womit man den Raum-Namen überschreiben kann, falls der zu lang wird oder so.

**Comment by Kunsi** [comment]
Gibts jetzt. Benutzt erstmal den Raum-Namen aus dem Schedule, wenn das Probleme macht, müssen wir das nochmal angucken.
